import SessionProvider from "@/contexts/SessionProvider";
import SnackbarProvider from "@/contexts/SnackbarProvider";
import Theme from "@/theme/Theme";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="id">
            <body>
                <Theme>
                    <SnackbarProvider>
                        <SessionProvider>
                            {children}
                        </SessionProvider>
                    </SnackbarProvider>
                </Theme>
            </body>
        </html>
    );
}
